---

# Template over files with those variables
- name: Interface | Template over interfaces file
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644

# Template over the wpa supplicant and reboot the host
- name: Interface | Template over wpa_supplicant file; prompt for ssid and psk.
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf  owner=root group=root mode=0644

# Force the pi config and reboot
-  debug: msg="Config Reload and Reboot"
   notify:
    - reboot
    - wait for reboot
   changed_when: true

# Force it to run these ^ handlers now, rather than at the end.
- meta: flush_handlers
