---

# Template over files with those variables
- name: Interface | Template over interfaces file
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644

# Template over the wpa supplicant and reboot the host
- name: Interface | Template over wpa_supplicant file; prompt for ssid and psk.
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf  owner=root group=root mode=0644

# Forcing task state to change in order to trigger the notify.
# Notify will only trigger when a task state is 'changed'
- name: Remove the file.
  file: path=/tmp/tempansiblefile state=absent

- name: Touch a file to instigate the reboot.
  file: path=/tmp/tempansiblefile state=touch
  notify:
    - reboot
    - wait for reboot
