---

# Install passlib, which is required for the password hashing in the next step.

# Change the password for the pi user
# here we're hashing the password via jinja. It's also possible to do it directly
# in the vars_prompt.
- name: Creating user "{{ uusername }}" with admin access
  user: name={{ uusername }} password={{ upassword |password_hash('sha512') }} groups=pi
