---

# Install passlib, which is required for the password hashing in the next step.

# Add a user
- name: USER | Add user to the system
  user:
    name: pi
    shell: /bin/bash
    groups: pi
    home: /home/pi
    createhome: yes
    password: "{{ upassword | password_hash('sha512') }}"
  register: u
  when: upassword != ""

# Set the authorized keys
- name: AUTHORIZED KEYS | Install SSH public key to pi user
  authorized_key:
    user: pi
    key: "{{ ssh_pubkey }}"
  when: ssh_pubkey is defined

# Template a sudoers file
- name: TEMPLATE | Create sudoers file
  template:
    src: etc/sudoers.d/ansible.j2
    dest: /etc/sudoers.d/ansible
    mode: 0440
    validate: 'visudo -cf %s'
  when: u.changed
