---
- name: apply raspi-config
  command: raspi-config --apply-os-config
  # using the Ansible blog post solution:
  # https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back

- name: reboot
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: false

- name: wait for reboot
  local_action:
    module: wait_for
      host="{{ inventory_hostname }}"
      port=22
      delay=1
      timeout=300
  sudo: false
