
---
- name: upgrade apt system
  apt: upgrade=yes update_cache=yes
  tags: update_os

- name: Install base
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600 force=yes
  with_items:
    - tmux
    - vim
    - git-core
    - build-essential
    - openssl
    - libssl-dev
    - pkg-config
    - python-dev
    - curl
    - htop
    - monit
    - mlocate

- name: Switch keyboard layout
  lineinfile: dest=/etc/default/keyboard regexp=XKBLAYOUT line='XKBLAYOUT="{{ keyboard_layout }}"'

  # Resize file system
- name: ensure filesystem is resized
  expand_fs:
  when: raspi_config_expanded_filesystem == true
  tags: gpu_ram_cpu

# Memory split between GPU and RAM and CPU parameters
- name: ensure mem split
  pi_boot_config: config_vals=gpu_mem={{raspi_config_memory_split_gpu}}
  notify:
    - apply raspi-config
    - reboot
  tags: gpu_ram_cpu

# This looks a bit unecessary, so commented but copied from
# source repo in case its useful: https://github.com/mikolak-net/ansible-raspi-config/blob/master/vars/main.yml

#- name: ensure correct CPU parameters for Pi2
#  ensure_pi2_oc:
#  args:
#    cpu_types: "{{raspi_config_pi_cpu}}"
#  when: raspi_config_ensure_optimal_cpu_params
#  notify:
#    - apply raspi-config
#    - reboot
#  tags: gpu_ram_cpu
